services:
  cli-proxy-api:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8317"
    volumes:
      - ./config.yaml:/CLIProxyAPI/config.yaml
      - ./data/data:/root/.cli-proxy-api
      - ./data/logs:/CLIProxyAPI/logs
      - ./data/plugins:/CLIProxyAPI/plugins
    image: eceasy/cli-proxy-api:v8.0.22
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
