networks:
    1panel-network:
        external: true
services:
    silo:
        command: "server /data --address :9000 --console-address :9001"
        container_name: ${CONTAINER_NAME}
        environment:
            MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
            MINIO_BROWSER_SESSION_DURATION: ${MINIO_BROWSER_SESSION_DURATION}
            MINIO_ROOT_PASSWORD: ${PANEL_MINIO_ROOT_PASSWORD}
            MINIO_ROOT_USER: ${PANEL_MINIO_ROOT_USER}
            MINIO_SERVER_URL: ${MINIO_SERVER_URL}
        image: pgsty/silo:RELEASE.2026-09-16T00-00-00Z-distroless
        labels:
            createdBy: Apps
        logging:
            driver: json-file
            options:
                max-file: "10"
                max-size: 5M
        networks:
            - 1panel-network
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:9001
            - ${HOST_IP}:${PANEL_APP_PORT_API}:9000
        restart: always
        volumes:
            - ./data:/data
            - ./certs:/root/.minio/certs
